<?php

use Illuminate\Database\Seeder;

class RestaurantsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('restaurants')->delete();
        
        \DB::table('restaurants')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name_en' => 'THE GREAT BURGER',
                'name_ja' => 'ザ グレートバーガー',
                'name_slug' => 'the-great-burger',
                'latitude' => '35.666215',
                'longitude' => '139.704697',
                'address_1' => '6-12-5 Jingumae',
                'address_2' => '',
                'address_3' => '',
                'municipality' => 'Shibuya',
                'prefecture' => 'Tokyo',
                'postcode' => '',
                'country' => 'JA',
                'has_nonsmoking' => 1,
                'has_vegetarian' => 0,
                'created_at' => '2016-11-14 02:16:41',
                'updated_at' => '2016-11-14 02:16:41',
                'user_id' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name_en' => 'BLACOWS',
                'name_ja' => 'ブラッカウズ',
                'name_slug' => 'blacows',
                'latitude' => '35.649398',
                'longitude' => '139.707092',
                'address_1' => '2-11-9 Ebisunishi',
                'address_2' => '',
                'address_3' => '',
                'municipality' => 'Shibuya',
                'prefecture' => 'Tokyo',
                'postcode' => '',
                'country' => 'JA',
                'has_nonsmoking' => 1,
                'has_vegetarian' => 0,
                'created_at' => '2016-11-14 02:24:31',
                'updated_at' => '2016-11-14 02:24:31',
                'user_id' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name_en' => 'Burger Mania',
                'name_ja' => 'バーガーマニア 恵比寿店',
                'name_slug' => 'burger-mania',
                'latitude' => '35.645999',
                'longitude' => '139.713080',
                'address_1' => '4-9-5 Ebisu',
                'address_2' => 'Mansion New Ebisu',
                'address_3' => '1F',
                'municipality' => 'Shibuya',
                'prefecture' => 'Tokyo',
                'postcode' => '',
                'country' => 'JA',
                'has_nonsmoking' => 1,
                'has_vegetarian' => 0,
                'created_at' => '2016-11-14 02:28:07',
                'updated_at' => '2016-11-14 02:28:07',
                'user_id' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name_en' => 'MARTINIBURGER',
                'name_ja' => 'マティーニバーガー',
                'name_slug' => 'martiniburger',
                'latitude' => '35.705582',
                'longitude' => '139.731096',
                'address_1' => '31 Nakazatocho',
                'address_2' => '',
                'address_3' => '',
                'municipality' => 'Shinjuku',
                'prefecture' => 'Tokyo',
                'postcode' => '',
                'country' => 'JA',
                'has_nonsmoking' => 1,
                'has_vegetarian' => 0,
                'created_at' => '2016-11-14 02:33:14',
                'updated_at' => '2016-11-14 02:33:14',
                'user_id' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'name_en' => 'homeys',
                'name_ja' => 'ホーミーズ',
                'name_slug' => 'homeys',
                'latitude' => '35.712012',
                'longitude' => '139.707854',
                'address_1' => '2-9-1 Takadanobaba',
                'address_2' => '',
                'address_3' => '',
                'municipality' => 'Shinjuku',
                'prefecture' => 'Tokyo',
                'postcode' => '',
                'country' => 'JA',
                'has_nonsmoking' => 0,
                'has_vegetarian' => 0,
                'created_at' => '2016-11-14 02:36:41',
                'updated_at' => '2016-11-14 02:36:41',
                'user_id' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'name_en' => 'GORI-GORI BURGER TAPROOM',
                'name_ja' => 'ゴリゴリバーガー タップルーム',
                'name_slug' => 'gori-gori-burger-taproom',
                'latitude' => '35.661649',
                'longitude' => '139.727720',
                'address_1' => '1-2-3 Nishiazabu',
                'address_2' => '',
                'address_3' => '1F',
                'municipality' => 'Minato',
                'prefecture' => 'Tokyo',
                'postcode' => '',
                'country' => 'JA',
                'has_nonsmoking' => 1,
                'has_vegetarian' => 0,
                'created_at' => '2016-11-14 02:41:27',
                'updated_at' => '2016-11-14 02:41:27',
                'user_id' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'name_en' => 'Harakara Minami Aoyama',
                'name_ja' => 'ハラカラ 南青山店',
                'name_slug' => 'harakara-minami-aoyama',
                'latitude' => '35.667549',
                'longitude' => '139.715286',
                'address_1' => '3-8-2 Minamiaoyama',
                'address_2' => '',
                'address_3' => '',
                'municipality' => 'Minato',
                'prefecture' => 'Tokyo',
                'postcode' => '',
                'country' => 'JA',
                'has_nonsmoking' => 1,
                'has_vegetarian' => 0,
                'created_at' => '2016-11-14 02:44:27',
                'updated_at' => '2016-11-14 02:44:27',
                'user_id' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'name_en' => 'Teddy\'s Bigger Burgers Omotesando',
                'name_ja' => 'テディーズ ビガー バーガー 表参道店',
                'name_slug' => 'teddy-s-bigger-burgers-omotesando',
                'latitude' => '35.667159',
                'longitude' => '139.704223',
                'address_1' => '6-28-5 Jingumae',
                'address_2' => 'Miyazaki Bldg.',
                'address_3' => '2F',
                'municipality' => 'Shibuya',
                'prefecture' => 'Tokyo',
                'postcode' => '',
                'country' => 'JA',
                'has_nonsmoking' => 1,
                'has_vegetarian' => 0,
                'created_at' => '2016-11-14 02:46:40',
                'updated_at' => '2016-11-14 02:46:40',
                'user_id' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'name_en' => 'COCKTAIL HAMBURGERS',
                'name_ja' => 'コックテイル ハンバーガーズ',
                'name_slug' => 'cocktail-hamburgers',
                'latitude' => '35.701789',
                'longitude' => '139.542243',
                'address_1' => '2-1-22 Kyonancho',
                'address_2' => '',
                'address_3' => '1F',
                'municipality' => 'Musashino',
                'prefecture' => 'Tokyo',
                'postcode' => '',
                'country' => 'JA',
                'has_nonsmoking' => 1,
                'has_vegetarian' => 0,
                'created_at' => '2016-11-14 02:49:28',
                'updated_at' => '2016-11-14 02:49:28',
                'user_id' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name_en' => 'BAREBURGER Ginza',
                'name_ja' => 'BAREBURGER 銀座店',
                'name_slug' => 'bareburger-ginza',
                'latitude' => '35.672184',
                'longitude' => '139.762451',
                'address_1' => '5-2-1 Ginza',
                'address_2' => 'Tokyu Plaza Ginza',
                'address_3' => '10F',
                'municipality' => 'Chuo',
                'prefecture' => 'Tokyo',
                'postcode' => '',
                'country' => 'JA',
                'has_nonsmoking' => 1,
                'has_vegetarian' => 0,
                'created_at' => '2016-11-14 02:52:22',
                'updated_at' => '2016-11-14 02:52:22',
                'user_id' => 1,
            ),
        ));
        
        
    }
}
